name: SOOS SCA Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  synchronous-analysis-with-blocking-result:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@ce8cb0a6d90fb0bceff89e7d66ad66f52fe3e658
      with:
        project_name: "soos-api-client"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}